### PR TITLE
Start next server with PORT env

### PR DESCRIPTION
**Pull request by konrad-glowacki**
If somebody will decide to change the PORT on our servers, then customer applications will be still working.

### CODE REVIEW

**Comment by webkrak** [comment]
If $PORT is not specified then port will be 3000 as is now for next.js

**Comment by thed00de** [comment]
@matt-landers @webkrak This is a good idea but I have a couple of thoughts.

8080 is the port, it is set by knative and knative also sets the $PORT env var (so it will ALWAYS be present).
3000 will NOT work on our platform as it is - I'm concerned its presence is misleading.

If 8080 being the default is an issue i.e. it is not the node default and hence not the default in a node devs heads then we could entertain the idea of changing the knative default from 8080 to 3000???

$PORT should be mentioned somewhere that is obvious to the user that THEY should NOT set an env var with that name.

There is further confusion here as really, apart from the app within the container binding to port 8080 the user never has to think to use 8080 again i.e. the url does not specify port 8080, port 80 is forwarded to 8080 behind the scenes. So having our customers to be aware of 8080 in one area and then not be consistent elsewhere could cause some confusion.

Maybe the bottom line is that the customers should NOT be concerned with these details at all, is there any way we could completely hide it from them or at least make it a requirement to bind to $PORT env var only.

**Comment by webkrak** [comment]
3000 is a very common port in local development env. Normally developers don't specify env PORT so by default will take 3000. Anyway, next.js is working to take default env $PORT, so in the near future will be simpler, just `npm start`.

**Comment by webkrak** [comment]
Ok, I made a small modification to not do a lot of changes. Still, we got port 8080 as previously but first will take env PORT if is defined. Not a big change. This will be fine?

**Review by matt-landers — COMMENTED** [review]
This doesn't work on Windows

**Comment by webkrak** [comment]
> This doesn't work on Windows

Thanks for checking. I will search for another solution.

**Pull request closed without merging**
